routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\AdminController;

//use App\Http\Controllers\Admin\OrderController;
Route::middleware("admin.guest")->match(['get', 'post'], '/login', "Admin\AuthController@login")->name("login");
Route::match(['post'], '/logout', "Admin\AuthController@logout")->name("logout");
Route::middleware("admin.auth")->group(function() {
    Route::get("dashboard", "Admin\DashboardController@dashboard")->name("dashboard");
    Route::any("profile", "Admin\AuthController@profile")->name("profile");
    Route::any("changePassword", "Admin\AuthController@changePassAdmin")->name("changePass");
    // route Category Admin
    Route::group(['prefix' => 'category', 'as'=>'category.'], function() {
        Route::get('/', [CategoryController::class, 'viewCategory'])->name('view');
        Route::POST('store', [CategoryController::class, 'storeCategory'])->name('store');
        Route::GET('edit-category/{id}', [CategoryController::class, 'editCategory'])->name('edit');
        Route::POST('update/{id}', [CategoryController::class, 'updateCategory'])->name('update');
        Route::GET('delete/{id}', [CategoryController::class, 'deleteCategory'])->name('delete');
    });

    // route country Admin
    Route::group(['prefix' => 'country', 'as'=>'country.'], function() {
        Route::get('/', [CountryController::class, 'index'])->name('view');
        Route::POST('store', [CountryController::class, 'store'])->name('store');
        Route::GET('edit/{id}', [CountryController::class, 'edit'])->name('edit');
        Route::POST('update/{id}', [CountryController::class, 'update'])->name('update');
        Route::GET('delete/{id}', [CountryController::class, 'delete'])->name('delete');
    });

    //route slider
    Route::group(['prefix' => 'slider', 'as'=>'slider.'], function() {
        Route::get('/', [SliderController::class, 'manageSlider'])->name('manage');
        Route::POST('store', [SliderController::class, 'storeSlider'])->name('store');
        Route::GET('edit/{id}', [SliderController::class, 'editSlider'])->name('edit');
        Route::POST('update/{id}', [SliderController::class, 'updateSlider'])->name('update');
        Route::GET('delete/{id}', [SliderController::class, 'deleteSlider'])->name('delete');
        Route::get('inactive/{id}', [SliderController::class, 'inactiveSlider'])->name('inactive');
        Route::get('active/{id}', [SliderController::class, 'activeSlider'])->name('active');
    });

    // route product
    Route::group(['prefix' => 'product', 'as'=>'product.'], function() {
        Route::get('add', [ProductController::class, 'addProduct'])->name('add');
        Route::POST('save', [ProductController::class, 'saveProduct'])->name('save');
        Route::get('manage', [ProductController::class, 'manageProduct'])->name('manage');
        Route::get('edit/{id}', [ProductController::class, 'editProduct'])->name('edit');
        Route::POST('update', [ProductController::class, 'updateProduct'])->name('update');
        Route::POST('update/multiImage', [ProductController::class, 'updateMultiImage'])->name('updateMultiImage');
        Route::get('edit/{id}', [ProductController::class, 'editProduct'])->name('edit');
        Route::get('deleteMultiImage/{id}', [ProductController::class, 'deleteMultiImage'])->name('deleteMultiImage');
        Route::get('active/{id}', [ProductController::class, 'activeProduct'])->name('active');
        Route::get('inactive/{id}', [ProductController::class, 'inactiveProduct'])->name('inactive');
        Route::get('delete/{id}', [ProductController::class, 'deleteProduct'])->name('delete');
    });

    // route order admin
    Route::group(['prefix' => 'order', 'as'=>'order.'], function() {
        Route::get('pending', [OrderController::class, 'managePendingOrder'])->name('managePendingOrder');
        Route::get('detail/{order_id}', [OrderController::class, 'detailOrder'])->name('detail');
        Route::get('pending/processing/{order_id}', [OrderController::class, 'updateProcessingOrder']);
        Route::get('processing', [OrderController::class, 'manageProcessingOrder'])->name('manageProcessingOrder');
        Route::get('processing/shipped/{order_id}', [OrderController::class, 'updateShippedOrder']);
        Route::get('shipped', [OrderController::class, 'manageShippedOrder'])->name('manageShippedOrder');
        Route::get('shipped/delivered/{order_id}', [OrderController::class, 'updateDeliveredOrder']);
        Route::get('delivered', [OrderController::class, 'manageDeliveredOrder'])->name('manageDeliveredOrder');
        Route::get('delivered/return/{order_id}', [OrderController::class, 'updateReturnOrder']);
        Route::get('cancel', [OrderController::class, 'manageCancelOrder'])->name('manageCancelOrder');
        Route::get('update-cancel/{order_id}', [OrderController::class, 'updateCancelOrder'])->name('updateCancelOrder');
        Route::get('invoice/{order_id}', [OrderController::class, 'invoiceOrder'])->name('invoice');
        Route::get('return', [OrderController::class, 'manageReturnOrder'])->name('manageReturnOrder');
        Route::get('return/success/{id}', [OrderController::class, 'returnSuccess'])->name('returnSuccess');
    });
    // route order admin
    Route::group(['prefix' => 'contact', 'as'=>'contact.'], function() {
        Route::get('pending', [ContactController::class, 'index'])->name('view');
    });

    // route manage admin
    Route::group(['prefix' => 'adminRole','middleware'=>['CheckRole']], function() {
        Route::get('manage', [AdminController::class, 'manageAdmin'])->name('adminRole.manage');
        Route::get('add', [AdminController::class, 'addAdmin'])->name('adminRole.add');
        Route::post('store', [AdminController::class, 'storeAdmin'])->name('adminRole.store');
        Route::get('edit/{id}', [AdminController::class, 'editAdmin'])->name('adminRole.edit');
        Route::get('delete/{id}', [AdminController::class, 'deleteAdmin'])->name('adminRole.delete');
        Route::post('update/{id}', [AdminController::class, 'updateAdmin'])->name('adminRole.update');
        Route::post('delete/{id}', [AdminController::class, 'deleteAdmin'])->name('adminRole.delete');
    });
});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CategoryController;
use App\Models\Item;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('client.')->group(function () {
    Route::get('/', [HomeController::class, "index"])->name("index");
    Route::get('/products',[ProductController::class, "index"])->name("products");
    Route::get('/product/{slug}',[ProductController::class, "detail"])->name("products.detail");
    Route::get('/cart',[CartController::class, "index"])->name("carts");
    Route::post('/add-to-cart',[CartController::class, "addToCart"])->name("cart.add");
    Route::post('/update-to-cart',[CartController::class, "updateToCart"])->name("cart.update");
    Route::post('/delete-to-cart',[CartController::class, "deleteToCart"])->name("cart.delete");
    Route::get('/get-total-cart',[CartController::class, "getTotalCart"])->name("cart.get.total.cart");
    Route::get('/get-small-cart',[CartController::class, "getSmallCart"])->name("cart.get.small.cart");
    Route::get('/category/{slug}', [CategoryController::class, 'index'])->name('category');
    Route::any("checkout", [CartController::class, "checkout"])->name("checkout");
    Route::any("callback-momo", [CartController::class, "callback"])->name("callback.momo");
    Route::get('/about', [HomeController::class, 'about'])->name('about');
    Route::post('/contact', [HomeController::class, 'contact'])->name('contact');
    Route::get('/detailV2', [CategoryController::class, function(){
        return view('frontend_clone.frontend.detailV2');
    }]);
});



Route::get("/test", function() {
//    $check =  Item::with('parts')
//     ->whereHas('parts', function($query) {
//        $query->whereNotNull('name');
//     })
//     ->get();

$check = Item::whereHas('parts', function($query) {
         $query->where('name','part2');
    })
    ->get();
    return $check;
});

Auth::routes();

Route::get('user/logout', function() {
     auth()->guard("web")->logout();
     return back();
})->name('user.logout');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/frontend_clone/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>


    <!-- Customizable CSS -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">


    <!-- Icons/Glyphs -->
    <link rel="stylesheet" href="{{asset('frontend_clone/css/product_detail.css')}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/main.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/style.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/media.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/products.css")}}">
    <link rel="stylesheet" href="{{asset('frontend_clone/css/lightslider.css')}}">
    <script src="{{asset("frontend_clone/js/btnSigIn.js")}}"></script>
    <meta name="viewport" content="width=device-width, inital-scale=1.0">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/validate.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/font/fontawesome-free-6.1.2-web/css/all.min.css")}}" >
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{{asset("frontend_clone/js/jquery.validate.min.js")}}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
    @livewireStyles

{{--    <link rel="stylesheet" href="assets/css/bootstrap.min.css">--}}
{{--    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">--}}
{{--    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>--}}
{{--    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800&display=swap" rel="stylesheet">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">--}}
@stack("css")
    <title>HiBeYo</title>
</head>
<body>
   <div class="all">

      <!-- Header -->
    @include("frontend_clone.body.header")
      <div class="content">
            @yield("content")
      </div>
      <!-- FOOTER -->
      @include("frontend_clone.body.footer")

       <div id="cd-cart">
            {{--  ajax mini cart   --}}
       </div> <!-- cd-cart -->
   </div>

   @include("frontend_clone.body.authenticate")
</body>
<script src="{{asset('frontend_clone/js/lightslider.js')}}"></script>
<script src="{{asset('frontend_clone/js/product_detail.js')}}"></script>
<script src="{{asset('frontend_clone/js/modernizr.js')}}"></script>
<script src="{{asset('frontend_clone/js/main.js')}}"></script>
{{--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>--}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@livewireScripts


<script>
    const URL_ROOT_IMAGE = "{{asset("/")}}";
    @if (Session::has('message'))
    var message = "{{Session::get('message')}}";
    var type = "{{Session::get('type')}}";
    console.log(message);
    switch(type) {
        case 'success':
        toastr.success(message);
        break;
        case 'info':
        toastr.info(message);
        break;
        case 'error':
        toastr.error(message);
        break;
        case 'warning':
        toastr.warning(message);
        break;
    }
    @endif
@if(Session::has("errors"))
    var objectErrors = <?php echo Session::get('errors') ?>;
    var htmlErrors = `<ul>`;
    Object.entries(objectErrors).forEach(([key, value]) => {
        htmlErrors += `<li>${value}</li>`;
    });
    htmlErrors+= `</ul>`;
    toastr.error(htmlErrors);
@endif
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });
    function showToast(type, message) {
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })

        Toast.fire({
            icon: type,
            title: message

        })
    }
    function addToCart(event, productId,qty=1) {
        event.preventDefault();
        $.ajax({
            type: "POST",
            data:{productId, qty},
            url: '/add-to-cart',
            dataType: "JSON",
            success: function (data) {
                if(data.result) {
                    showSmallCart();
                    showToast("success",data.message);
                }
                else {
                    showToast("error",data.message);
                }
            },
            error: function(data) {
                alert(data.message);
            },
        });
    }
    function showSmallCart() {
        $.ajax({
            type: "get",
            data:{},
            url: '/get-small-cart',
            dataType: "JSON",
            success: function (data) {
                if(data.result) {
                    if(data.data.countCart == 0) {
                        $(".count-data-cart").empty();
                        let html = `<h2>Giỏ hàng của bạn rỗng</h2>`;
                        $("#cd-cart").html(html);
                    } else {
                        $(".count-data-cart").text(data.data.countCart);
                        let html = `<h2>Giỏ hàng của bạn</h2>`;
                            html += `<ul class="cd-cart-items">`;
                        $.each( data.data.dataCart, function( key, value ) {
                            html += `<li>
                                        <div style="display: flex;align-items: center; width: 85%;">
                                            <div class="left">
                                                <img width="100" height="100" src="${URL_ROOT_IMAGE+value.options.image}" alt="">
                                            </div>
                                            <div class="right">
                                                <span class="cd-qty">${value.qty}x</span>${value.name}
                                                <div class="cd-price">${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(value.price)}</div>
                                            </div>
                                        </div>
                                        <a href="#0" style="text-align: center;
                                                        background: red;
                                                        color: #fff;
                                                        display: flex;
                                                        justify-content: center;
                                                        align-items: center;" onclick="delProductCart('${value.rowId}',${value.id})"  class="cd-item-remove cd-img-replace"><i class="fa-solid fa-trash"></i></a>
                                    </li>`;
                        });

                        html += `</ul>
                        <div class="cd-cart-total">
                            <p>Tổng đơn hàng: <span>${data.data.totalCart} ₫</span></p>
                        </div> <!-- cd-cart-total -->
                        <a href="/checkout" style="text-decoration: none;" class="checkout-btn">Thanh toán</a>
                        <a class="cd-go-cart" style="text-decoration: none;" href="{{route("client.carts")}}">Đi tới giỏ hàng</a>`;
                        $("#cd-cart").html(html);
                    }
                }
            },
            error: function(data) {
                alert(data.message);
            },
        });
    }
    function delProductCart(rowId, productId) {
        $.ajax({
            type: "POST",
            data:{rowId},
            url: '/delete-to-cart',
            dataType: "JSON",
            success: function (data) {
                if(data.result) {
                    showToast("success",data.message);
                    $("#item-data-cart"+productId).remove();
                    if($('#totalValueOrder').length > 0) {
                        getTotalCart();
                    }
                    showSmallCart();
                }
                else {
                    showToast("error",data.message);
                }
            },
            error: function(data) {
                showToast("error",data.message);
            },
        });
    }
    showSmallCart();
</script>


</html>

resources/views/frontend_clone/layouts/masterV2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>


    <!-- Customizable CSS -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">


    <!-- Icons/Glyphs -->
    <link rel="stylesheet" href="{{asset('frontend_clone/css/product_detail.css')}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/main.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/style.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/media.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/products.css")}}">
    <link rel="stylesheet" href="{{asset('frontend_clone/css/lightslider.css')}}">
    <script src="{{asset("frontend_clone/js/btnSigIn.js")}}"></script>
    <meta name="viewport" content="width=device-width, inital-scale=1.0">
    <link rel="stylesheet" href="{{asset("frontend_clone/css/validate.css")}}">
    <link rel="stylesheet" href="{{asset("frontend_clone/font/fontawesome-free-6.1.2-web/css/all.min.css")}}" >
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{{asset("frontend_clone/js/jquery.validate.min.js")}}"></script>

    @livewireStyles

{{--    <link rel="stylesheet" href="assets/css/bootstrap.min.css">--}}
{{--    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">--}}
{{--    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>--}}
{{--    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800&display=swap" rel="stylesheet">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">--}}

    <title>HiBeYo</title>
</head>
<body>
   <div class="all">

      <!-- Header -->
    @include("frontend_clone.body.headerV2")
      <div class="content">
            @yield("content")
      </div>
      <!-- FOOTER -->
      @include("frontend_clone.body.footer")


   </div>

   @include("frontend_clone.body.authenticate")
</body>
<script src="{{asset('frontend_clone/js/lightslider.js')}}"></script>
<script src="{{asset('frontend_clone/js/product_detail.js')}}"></script>
<script src="{{asset('frontend_clone/js/modernizr.js')}}"></script>
<script src="{{asset('frontend_clone/js/main.js')}}"></script>
{{--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>--}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@livewireScripts


<script>
    @if (Session::has('message'))
    var message = "{{Session::get('message')}}";
    var type = "{{Session::get('type')}}";
    console.log(message);
    switch(type) {
        case 'success':
        toastr.success(message);
        break;
        case 'info':
        toastr.info(message);
        break;
        case 'error':
        toastr.error(message);
        break;
        case 'warning':
        toastr.warning(message);
        break;
    }
    @endif

@if(Session::has("errors"))
    var objectErrors = <?php echo Session::get('errors') ?>;
    var htmlErrors = `<ul>`;
    Object.entries(objectErrors).forEach(([key, value]) => {
        htmlErrors += `<li>${value}</li>`;
    });
    htmlErrors+= `</ul>`;
    toastr.error(htmlErrors);
@endif
</>
</html>