routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\AdminController;

//use App\Http\Controllers\Admin\OrderController;
Route::middleware("admin.guest")->match(['get', 'post'], '/login', "Admin\AuthController@login")->name("login");
Route::match(['post'], '/logout', "Admin\AuthController@logout")->name("logout");
Route::middleware("admin.auth")->group(function() {
    Route::get("dashboard", "Admin\DashboardController@dashboard")->name("dashboard");
    Route::any("profile", "Admin\AuthController@profile")->name("profile");
    Route::any("changePassword", "Admin\AuthController@changePassAdmin")->name("changePass");
    // route Category Admin
    Route::group(['prefix' => 'category', 'as'=>'category.'], function() {
        Route::get('/', [CategoryController::class, 'viewCategory'])->name('view');
        Route::POST('store', [CategoryController::class, 'storeCategory'])->name('store');
        Route::GET('edit-category/{id}', [CategoryController::class, 'editCategory'])->name('edit');
        Route::POST('update/{id}', [CategoryController::class, 'updateCategory'])->name('update');
        Route::GET('delete/{id}', [CategoryController::class, 'deleteCategory'])->name('delete');
    });

    // route country Admin
    Route::group(['prefix' => 'country', 'as'=>'country.'], function() {
        Route::get('/', [CountryController::class, 'index'])->name('view');
        Route::POST('store', [CountryController::class, 'store'])->name('store');
        Route::GET('edit/{id}', [CountryController::class, 'edit'])->name('edit');
        Route::POST('update/{id}', [CountryController::class, 'update'])->name('update');
        Route::GET('delete/{id}', [CountryController::class, 'delete'])->name('delete');
    });

    //route slider
    Route::group(['prefix' => 'slider', 'as'=>'slider.'], function() {
        Route::get('/', [SliderController::class, 'manageSlider'])->name('manage');
        Route::POST('store', [SliderController::class, 'storeSlider'])->name('store');
        Route::GET('edit/{id}', [SliderController::class, 'editSlider'])->name('edit');
        Route::POST('update/{id}', [SliderController::class, 'updateSlider'])->name('update');
        Route::GET('delete/{id}', [SliderController::class, 'deleteSlider'])->name('delete');
        Route::get('inactive/{id}', [SliderController::class, 'inactiveSlider'])->name('inactive');
        Route::get('active/{id}', [SliderController::class, 'activeSlider'])->name('active');
    });

    // route product
    Route::group(['prefix' => 'product', 'as'=>'product.'], function() {
        Route::get('add', [ProductController::class, 'addProduct'])->name('add');
        Route::POST('save', [ProductController::class, 'saveProduct'])->name('save');
        Route::get('manage', [ProductController::class, 'manageProduct'])->name('manage');
        Route::get('edit/{id}', [ProductController::class, 'editProduct'])->name('edit');
        Route::POST('update', [ProductController::class, 'updateProduct'])->name('update');
        Route::POST('update/multiImage', [ProductController::class, 'updateMultiImage'])->name('updateMultiImage');
        Route::get('edit/{id}', [ProductController::class, 'editProduct'])->name('edit');
        Route::get('deleteMultiImage/{id}', [ProductController::class, 'deleteMultiImage'])->name('deleteMultiImage');
        Route::get('active/{id}', [ProductController::class, 'activeProduct'])->name('active');
        Route::get('inactive/{id}', [ProductController::class, 'inactiveProduct'])->name('inactive');
        Route::get('delete/{id}', [ProductController::class, 'deleteProduct'])->name('delete');
    });

    // route order admin
    Route::group(['prefix' => 'order', 'as'=>'order.'], function() {
        Route::get('pending', [OrderController::class, 'managePendingOrder'])->name('managePendingOrder');
        Route::get('detail/{order_id}', [OrderController::class, 'detailOrder'])->name('detail');
        Route::get('pending/processing/{order_id}', [OrderController::class, 'updateProcessingOrder']);
        Route::get('processing', [OrderController::class, 'manageProcessingOrder'])->name('manageProcessingOrder');
        Route::get('processing/shipped/{order_id}', [OrderController::class, 'updateShippedOrder']);
        Route::get('shipped', [OrderController::class, 'manageShippedOrder'])->name('manageShippedOrder');
        Route::get('shipped/delivered/{order_id}', [OrderController::class, 'updateDeliveredOrder']);
        Route::get('delivered', [OrderController::class, 'manageDeliveredOrder'])->name('manageDeliveredOrder');
        Route::get('delivered/return/{order_id}', [OrderController::class, 'updateReturnOrder']);
        Route::get('cancel', [OrderController::class, 'manageCancelOrder'])->name('manageCancelOrder');
        Route::get('update-cancel/{order_id}', [OrderController::class, 'updateCancelOrder'])->name('updateCancelOrder');
        Route::get('invoice/{order_id}', [OrderController::class, 'invoiceOrder'])->name('invoice');
        Route::get('return', [OrderController::class, 'manageReturnOrder'])->name('manageReturnOrder');
        Route::get('return/success/{id}', [OrderController::class, 'returnSuccess'])->name('returnSuccess');
    });
    // route order admin
    Route::group(['prefix' => 'contact', 'as'=>'contact.'], function() {
        Route::get('pending', [ContactController::class, 'index'])->name('view');
    });

    // route manage admin
    Route::group(['prefix' => 'adminRole','middleware'=>['CheckRole']], function() {
        Route::get('manage', [AdminController::class, 'manageAdmin'])->name('adminRole.manage');
        Route::get('add', [AdminController::class, 'addAdmin'])->name('adminRole.add');
        Route::post('store', [AdminController::class, 'storeAdmin'])->name('adminRole.store');
        Route::get('edit/{id}', [AdminController::class, 'editAdmin'])->name('adminRole.edit');
        Route::get('delete/{id}', [AdminController::class, 'deleteAdmin'])->name('adminRole.delete');
        Route::post('update/{id}', [AdminController::class, 'updateAdmin'])->name('adminRole.update');
        Route::post('delete/{id}', [AdminController::class, 'deleteAdmin'])->name('adminRole.delete');
    });
});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\CategoryController;
use App\Models\Item;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('client.')->group(function () {
    Route::get('/', [HomeController::class, "index"])->name("index");
    Route::get('/products',[ProductController::class, "index"])->name("products");
    Route::get('/product/{slug}',[ProductController::class, "detail"])->name("products.detail");
    Route::get('/cart',[CartController::class, "index"])->name("carts");
    Route::post('/add-to-cart',[CartController::class, "addToCart"])->name("cart.add");
    Route::post('/update-to-cart',[CartController::class, "updateToCart"])->name("cart.update");
    Route::post('/delete-to-cart',[CartController::class, "deleteToCart"])->name("cart.delete");
    Route::get('/get-total-cart',[CartController::class, "getTotalCart"])->name("cart.get.total.cart");
    Route::get('/get-small-cart',[CartController::class, "getSmallCart"])->name("cart.get.small.cart");
    Route::get('/category/{slug}', [CategoryController::class, 'index'])->name('category');
    Route::any("checkout", [CartController::class, "checkout"])->name("checkout");
    Route::any("callback-momo", [CartController::class, "callback"])->name("callback.momo");
    Route::get('/about', [HomeController::class, 'about'])->name('about');
    Route::post('/contact', [HomeController::class, 'contact'])->name('contact');
    Route::get('/detailV2', [CategoryController::class, function(){
        return view('frontend_clone.frontend.detailV2');
    }]);
});



Route::get("/test", function() {
//    $check =  Item::with('parts')
//     ->whereHas('parts', function($query) {
//        $query->whereNotNull('name');
//     })
//     ->get();

$check = Item::whereHas('parts', function($query) {
         $query->where('name','part2');
    })
    ->get();
    return $check;
});

Auth::routes();

Route::get('user/logout', function() {
     auth()->guard("web")->logout();
     return back();
})->name('user.logout');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/frontend_clone/frontend/category.blade.php
@extends("frontend_clone.layouts.master")
@section("content")
    <style>
        .price-show {
            display: flex;
            justify-content: space-around;
            padding-top: 13px;
        }
        .price-orderBy.active {
            background: hsl(180deg 51% 52%);
        }
    </style>
    <div class="content__link w-full">
       <div class="content__link__box container pad-1-lr">
          <div class="link__box__inside dis_flex text-fs-1 ">
             <a class="text__link" href="{{route("client.index")}}">Trang chủ</a>
             <i class="icon__text__link fa-solid fa-angle-right"></i>
             <a class="text__link" href="{{route("client.products")}}">Sản phẩm</a>
          </div>
       </div>
    </div>
    <div class="content__body container pad-1-lr">
       <div class="content__body__colum grid grid-clos-12">
          <div class="content__body__b1 col-span-3">
             <div class="body__b1 w-full">
                <!-- Box 1 -->
                <div class="b1__box1">
                   <p class="box__header text-tran">Mức giá</p>
                   <p class="box1__text">Giá tối thiểu</p>
                    <form action="{{$currentRoute}}" method="get">
                        <input type="hidden" name="price" value="{{request()->get("price")}}"/>
                        <div class="box1__text2__input">
                            <div class="text2__input pos-rela">
                                <input type="number" min="100000" name="min-price" value="{{old('min-price', request()->get('min-price'))}}" class="text2__input__box w-full">
                                <div class="text__input__inside pos-ab dis_flex">
                                    <p class="inside__text text-tran">VND</p>
                                </div>
                            </div>
                        </div>
                        <p class="box1__text">Giá tối đa</p>
                        <div class="box1__text3__input pos-rela">
                            <input type="number" min="100000" name="max-price" value="{{old('min-price', request()->get('max-price'))}}" class="text2__input__box w-full">
                            <div class="text__input__inside pos-ab dis_flex">
                                <p class="inside__text text-tran">VND</p>
                            </div>
                        </div>
                        <div class="box1__bnt w-full dis_flex ">
                            <button class="box1__bnt__inside text-nm pd-l-r-2 pd-tb-625">ÁP DỤNG</button>
                        </div>
                    </form>
                </div>
                <!-- Box 3 -->
{{--                <div class="b1__box3">--}}
{{--                   <div class="b1__box2">--}}
{{--                      <p class="box__header text-tran">loại sản phẩm</p>--}}

{{--                       @forelse($categories as $category)--}}
{{--                           <label class="box2__checkmark dis_flex text-nm algin_center pos-rela">--}}
{{--                               <input class="checkmark checkbox-category" {{in_array($category->id,$idCategoryChecked) ? "checked" : ""}} value="{{$category->id}}"  type="checkbox">--}}
{{--                               <div class="box2__checkmark__text w-full dis_flex text-nm">--}}
{{--                                   <p class="mg-0">{{$category->category_name_vn}}</p>--}}
{{--                                   <p class="opacity-3 mg-0">{{$category->products_count}}</p>--}}
{{--                               </div>--}}
{{--                               <span ></span>--}}
{{--                           </label>--}}
{{--                       @empty--}}
{{--                       @endforelse--}}
{{--                   </div>--}}
{{--                </div>--}}
             </div>
          </div>
          <div class="content__body__b2 col-span-9">
             <div class="body__b2">
                <div class="body__b2__header pd-tb-1">
                   <p class="body__b2__header__text text-tran text-fs-2">Danh sách sản phẩm {{$category->category_name_vn}}</p>
                </div>
                <div class="body__b2__nav pd-tb-625">
                   <div class="body__b2__nav__inside dis_flex algin_center pd-l-r-2">
                      <p class="nav__text text-nm">Sắp xếp theo</p>
                      <a class="nav__bnt text-tran pd-tb-625 btn-increase price-orderBy {{$priceSelected == "asc" ? "active" : ""}}" style="text-decoration: none;"  href="">Giá thấp đến cao</a>
                      <a class="nav__bnt text-tran pd-tb-625 btn-decrease price-orderBy {{$priceSelected == "desc" ? "active" : ""}}" style="text-decoration: none;" href="">Giá cao đến thấp</a>
                   </div>
                </div>
                <div class="body__b2__products grid grid-clos-4">
                   @forelse ($products as $product)
                   <a class="b2__products__all" href="{{route("client.products.detail", $product->product_slug_vn)}}">
                        <div class="b2__products">
                            <div class="b2__products__box dis_flex">
                                <div class="b2__products__box__img pos-rela">
                                    <img style="width:180px;" class="products__img" src="{{asset($product->mainImage[0]->url)}}" alt="">
                                </div>
                            </div>
                            <h4 class="products__text text-nm">{{$product->product_name_vn}}</h4>
                            @if(!is_null($product->discount_price) && $product->discount_price > 0)
                           <div class="price-show">
                               <p class="products__price" style="font-size:14px;text-decoration: line-through; color: #808080ba;">{{number_format($product->selling_price,0,",",",")}} Đ</p>
                               <p class="products__price" style="font-size:14px;">{{number_format($product->discount_price,0,",",",")}} Đ</p>
                           </div>
                            @else
                                <p class="products__price" style="padding-top: 15px;" >{{number_format($product->selling_price,0,",",",")}} Đ</p>
                            @endif
                        </div>
                    </a>
                   @empty
                    <h3>Rỗng</h3>
                   @endforelse
                </div>

                 {{ $products->links("paginate.custom") }}
          </div>
       </div>
    </div>
        <script>

            $(document).ready(function() {
                //update parameter when change filter
                function updateParameter(urlCurrent, key, value) {
                    let url = new URL(urlCurrent);
                    let search_params = url.searchParams;
                    // new value of "key" is set to "value"
                    search_params.set(key, value);
                    search_params.set('page', 1);
                    // change the search property of the main url
                    url.search = search_params.toString();
                    return url.toString();
                }
                $('.btn-increase').click(function(e) {
                    e.preventDefault();
                    window.location.href = updateParameter(window.location.href, 'price', "asc");
                });
                $('.btn-decrease').click(function(e) {
                    e.preventDefault();
                    window.location.href = updateParameter(window.location.href, 'price', "desc");
                });
                $('.checkbox-category').click(function(e) {
                    let idCategory = [];
                    $( '.checkbox-category' ).each( function( index, checkbox ) {
                        if(checkbox.checked) {
                            idCategory.push($(this).val());
                        }
                    });
                    window.location.href = updateParameter(window.location.href, 'category', JSON.stringify(idCategory));
                });
            })
        </script>
@endsection

resources/views/frontend_clone/frontend/product_detail.blade.php
@extends("frontend_clone.layouts.master")
@section("content")
<div class = "card-wrapper product-detail">
    <div class = "card">
        <!-- card left -->
        <div class = "product-imgs">
            <div class = "img-display">
                <div class = "img-showcase">
                    @foreach($product->images as $image)
                    <img  src = "{{asset($image->url)}}" alt = "shoe image">
                    @endforeach
                </div>
            </div>
            <div class = "img-select">
                @foreach($product->images as $key=>$image)
                    <div class = "img-item">
                        <a href = "#" data-id = "{{$key+1}}">
                            <img style="height: 140px;width: 140px;" src = "{{asset($image->url)}}" alt = "shoe image">
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
        <!-- card right -->
        <div class = "product-content">
            <h4 class = "product-title">{{$product->product_name_vn}}</h4>
            <a href = "{{route("client.category", $product->category->category_slug_vn)}}" class = "product-link">Xem nhiều sản phẩm hơn nữa tại đây</a>

            <div class = "product-price">
                <p class = "last-price">Giá cũ: <span>{{number_format($product->selling_price,0,",",",")}} Đ</span></p>
                <p class = "new-price">Giá mới: <span>{{number_format($product->discount_price,0,",",",")}} Đ</span></p>
            </div>

            <div class = "product-detail">
                <h2>Giới thiệu sản phẩm: </h2>
                <p>{!! $product->short_descp_vn !!}</p>
                <ul>
                    <li>Xuất xứ: <span>{{optional($product->country)->name}}</span></li>
                    <li>Dung tích: <span>{{$product->capacity}} {{\App\Models\Product::UNIT[$product->product_unit]}}</span></li>
                    <li>Tình trạng: <span>{{$product->product_qty > 0 ? "Còn hàng" : "Hết hàng"}}</span></li>
                    <li>Số lượng: <span>{{$product->product_qty}}</span></li>
                    <li>Tình trạng: <span>{{$product->product_qty > 0 ? "Còn hàng" : "Hết hàng"}}</span></li>
                    <li>Danh mục: <span>{{$product->category->category_name_vn}}</span></li>
                    <li>Vận chuyển: <span>Khu vực Hà Nội</span></li>
                    <li>Phí vận chuyển: <span>Free</span></li>
                </ul>
            </div>

            <div class = "purchase-info">
                <input id="qty-product" type = "number" min = "0" value = "1">
                <button type = "button" onclick="addToCart(event, {{$product->id}},$('#qty-product').val())" class = "btn">
                    Thêm giỏ hàng <i class = "fas fa-shopping-cart"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="container pad-1-lr">
    <div class="new-products__table__header text-tran">
        <h3 style="margin: 0;">Nội dung sản phẩm</h3>
    </div>
    <div class="content">
        {!! $product->long_descp_vn !!}
    </div>
</div>
<div class="best-sell__box container pad-1-lr" style="margin-top: 100px;">
    <div class="best-sell__box__header">
        <h4
        style="
            font-size: 2rem;
            color: #0098d2;
            text-align: center;
            background: #cbecf7;
            padding: 15px;
        "
        >Sản phẩm liên quan</h4>
    </div>
    <ul id="content-slider" class="content-slider">
        @forelse($productsRelated as $productRelated)
            <li>
                <a class="table__body__link border-left-none" href="{{route("client.products.detail",$productRelated->product_slug_vn)}}">
                    <div class="table__body__box">
                        <div class="body__box__img dis_flex">
                            <div class="img__inside pos-rela">
                                <img class="table__img" width="180" height="180" src="{{asset($productRelated->mainImage[0]->url)}}" alt="Sữa Hikid dê Hàn Quốc tăng chiều cao ">
                            </div>
                        </div>
                        <h4 class="body__box__text text-nm">Sữa Hikid dê Hàn Quốc tăng chiều cao </h4>
                        @if(!is_null($productRelated->discount_price) && $productRelated->discount_price > 0)
                            <div class="price-show">
                                <p class="products__price" style="font-size:14px;text-decoration: line-through; color: #808080ba;">{{number_format($productRelated->selling_price,0,",",",")}} Đ</p>
                                <p class="products__price" style="font-size:14px;">{{number_format($productRelated->discount_price,0,",",",")}} Đ</p>
                            </div>
                        @else
                            <p class="products__price" style="padding-top: 15px; font-size:14px;" >{{number_format($productRelated->selling_price,0,",",",")}} Đ</p>
                        @endif
                    </div>
                </a>
            </li>
        @empty
            <h4>Rỗng</h4>
        @endforelse

    </ul>
</div>
<script>
    $(document).ready(function() {
        $("#content-slider").lightSlider({
            auto:true,
            item:6,
            loop:true,
            keyPress:true
        });
    })
</script>
@endsection

{{--<script src="script.js"></script>--}}
{{--</body>--}}
{{--</html>--}}

resources/views/frontend_clone/frontend/product_list.blade.php
@extends("frontend_clone.layouts.master")
@section("content")
    <style>
        .price-show {
            display: flex;
            justify-content: space-around;
            padding-top: 13px;
        }
        .price-orderBy.active {
            background: hsl(180deg 51% 52%);
        }
    </style>
    <div class="content__link w-full">
       <div class="content__link__box container pad-1-lr">
          <div class="link__box__inside dis_flex text-fs-1 ">
             <a class="text__link" href="{{route("client.index")}}">Trang chủ</a>
             <i class="icon__text__link fa-solid fa-angle-right"></i>
             <a class="text__link" href="{{route("client.products")}}">Sản phẩm</a>
          </div>
       </div>
    </div>
    <div class="content__body container pad-1-lr">
       <div class="content__body__colum grid grid-clos-12">
          <div class="content__body__b1 col-span-3">
             <div class="body__b1 w-full">
                <!-- Box 1 -->
                <div class="b1__box1">
                   <p class="box__header text-tran">Mức giá</p>
                   <p class="box1__text">Giá tối thiểu</p>
                    <form action="{{$currentRoute}}" method="get">
                        {{-- check param có sẵn --}}

                        <input type="hidden" name="price" value="{{request()->get("price")}}"/>
                        <input type="hidden" name="category" value="{{request()->get("category")}}"/>
                        <div class="box1__text2__input">
                            <div class="text2__input pos-rela">
                                <input type="number" min="100000" name="min-price" value="{{old('min-price', request()->get('min-price'))}}" class="text2__input__box w-full">
                                <div class="text__input__inside pos-ab dis_flex">
                                    <p class="inside__text text-tran">VND</p>
                                </div>
                            </div>
                        </div>
                        <p class="box1__text">Giá tối đa</p>
                        <div class="box1__text3__input pos-rela">
                            <input type="number" min="100000" name="max-price" value="{{old('min-price', request()->get('max-price'))}}" class="text2__input__box w-full">
                            <div class="text__input__inside pos-ab dis_flex">
                                <p class="inside__text text-tran">VND</p>
                            </div>
                        </div>
                        <div class="box1__bnt w-full dis_flex ">
                            <button class="box1__bnt__inside text-nm pd-l-r-2 pd-tb-625">ÁP DỤNG</button>
                        </div>
                    </form>
                </div>
                <!-- Box 3 -->
                <div class="b1__box3">
                   <div class="b1__box2">
                      <p class="box__header text-tran">loại sản phẩm</p>

                       @forelse($categories as $category)
                           <label class="box2__checkmark dis_flex text-nm algin_center pos-rela">
                               <input class="checkmark checkbox-category" {{!empty($idCategoryChecked) && in_array($category->id,$idCategoryChecked) ? "checked" : ""}} value="{{$category->id}}"  type="checkbox">
                               <div class="box2__checkmark__text w-full dis_flex text-nm">
                                   <p class="mg-0">{{$category->category_name_vn}}</p>
                                   <p class="opacity-3 mg-0">{{$category->products_count}}</p>
                               </div>
                               <span ></span>
                           </label>
                       @empty
                       @endforelse
                   </div>
                </div>
             </div>
          </div>
          <div class="content__body__b2 col-span-9">
             <div class="body__b2">
                <div class="body__b2__header pd-tb-1">
                   <p class="body__b2__header__text text-tran text-fs-2">Danh sách sản phẩm</p>
                </div>
                <div class="body__b2__nav pd-tb-625">
                   <div class="body__b2__nav__inside dis_flex algin_center pd-l-r-2">
                      <p class="nav__text text-nm">Sắp xếp theo</p>
                      <a class="nav__bnt text-tran pd-tb-625 btn-increase price-orderBy {{$priceSelected == "asc" ? "active" : ""}}" style="text-decoration: none;"  href="">Giá thấp đến cao</a>
                      <a class="nav__bnt text-tran pd-tb-625 btn-decrease price-orderBy {{$priceSelected == "desc" ? "active" : ""}}" style="text-decoration: none;" href="">Giá cao đến thấp</a>
                   </div>
                </div>
                <div class="body__b2__products grid grid-clos-4">
                   @forelse ($products as $product)
                   <a class="b2__products__all" href="{{route("client.products.detail",$product->product_slug_vn)}}" style="position:relative;">
                        <div class="b2__products">
                            <div class="b2__products__box dis_flex">
                                <div class="b2__products__box__img pos-rela">
                                    <img style="width:180px;" class="products__img" src="{{asset($product->mainImage[0]->url)}}" alt="">
                                </div>
                            </div>
                            <span onclick="addToCart(event,{{ $product->id }})"><i style="position: absolute; top: 9px; right: 0; color: #e07fb0;" class="icon__cart fa-solid fa-cart-shopping"></i></span>
                            <h4 class="products__text text-nm">{{$product->product_name_vn}}</h4>
                            @if(!is_null($product->discount_price) && $product->discount_price > 0)
                           <div class="price-show">
                               <p class="products__price" style="font-size:14px;text-decoration: line-through; color: #808080ba;">{{number_format($product->selling_price,0,",",",")}} Đ</p>
                               <p class="products__price" style="font-size:14px;">{{number_format($product->discount_price,0,",",",")}} Đ</p>
                           </div>
                            @else
                                <p class="products__price" style="padding-top: 15px;" >{{number_format($product->selling_price,0,",",",")}} Đ</p>
                            @endif
                        </div>
                    </a>
                   @empty
                    <h3>Rỗng</h3>
                   @endforelse
                </div>

                 {{ $products->links("paginate.custom") }}
          </div>
       </div>
    </div>
        <script>

            $(document).ready(function() {
                //update parameter when change filter
                function updateParameter(urlCurrent, key, value) {
                    let url = new URL(urlCurrent);
                    let search_params = url.searchParams;
                    // new value of "key" is set to "value"
                    search_params.set(key, value);
                    search_params.set('page', 1);
                    // change the search property of the main url
                    url.search = search_params.toString();
                    return url.toString();
                }
                $('.btn-increase').click(function(e) {
                    e.preventDefault();
                    window.location.href = updateParameter(window.location.href, 'price', "asc");
                });
                $('.btn-decrease').click(function(e) {
                    e.preventDefault();
                    window.location.href = updateParameter(window.location.href, 'price', "desc");
                });
                $('.checkbox-category').click(function(e) {
                    let idCategory = [];
                    $( '.checkbox-category' ).each( function( index, checkbox ) {
                        if(checkbox.checked) {
                            idCategory.push($(this).val());
                        }
                    });
                    window.location.href = updateParameter(window.location.href, 'category', JSON.stringify(idCategory));
                });
            })
        </script>
@endsection